FROM nginx:1.21-alpine

RUN rm /etc/nginx/conf.d/default.conf

COPY ./deployluculucu.my.id.conf /etc/nginx/conf.d/deployluculucu.my.id.conf

COPY ./cvmirza.deployluculucu.my.id.conf /etc/nginx/conf.d/cvmirza.deployluculucu.my.id.conf